### ISSUE TITLE
input string 1 is invalid UTF-8

### ISSUE THREAD

**Issue by sneumann** [ipb-halle/MetFamily#43]
Currently with https://cloud.docker.com/u/sneumann/repository/docker/sneumann/metfamily 
I get at https://msbi.ipb-halle.de/MetFamily/ the error 
`input string 1 is invalid UTF-8`.

**Comment by Treutler** [comment]
Maybe an encoding issue or a bad character issue.
Compare to [this](https://github.com/smouksassi/ggplotwithyourdata/issues/16) issue.
Does this happen in the app and we have a stack trace?

**Comment by sneumann** [comment]
Fixed in the new images.
