### ISSUE TITLE
new MS-Dial format

### ISSUE THREAD

**Issue by korseby** [ipb-halle/MetFamily#44]
The format of the Height_.txt has changed since MS-Dial version 3.90.

A first look on the new format reveals the following changes:
- NO changes to the MSP
- a lot non-trivial changes to the Height_.txt that require some work

The new format of the Height_.txt is detectable. While the first 3 cells of the first column of the old format are empty, in the new format there are 4 empty cells. This is the result of a new row called "Batch ID”.

- new row: `Batch ID`
- new columns: `Reference RT`, `Reference m/z`, `MSI level`, `Comment`, `**Mannually modified**`, `Total score`, `RT similarity`

I also noticed a change in the handling of NA values: instead of `No record` now `null`, instead of `-1` now `null`.

The number precision has changed to the worse: now fewer decimal places!

You maybe have noticed **a typo in the column names**! So I suggest to wait a little until the bugs are fixed, otherwise we need to change the MetFamily code again and again with each bugfix.

**Comment by sneumann** [comment]
Some parsing code is here: https://github.com/ipb-halle/MetFamily/blob/5aa2e2da009d947eef7f89287558137a76cfe0bd/R/FragmentMatrixFunctions.R#L8

**Comment by Treutler** [comment]
Fixed in bbe66fb71f20fe9a44ea736d178560f535c70b97

**Comment by korseby** [comment]
I can confirm that we have a test file from version 3.90.

Have the latest changes made it to the MetFamilyDev on msbi or do we need to apply them?
