### ISSUE TITLE
Docker image is missing 'xcms'

### ISSUE THREAD

**Issue by nschan** [ipb-halle/MetFamily#84]
Hello,

I tried running the current `latest` docker image, but it seems that the `xcms` library is not included in the container:

```
Warning: Error in library: there is no package called ‘xcms’
  44: <Anonymous>
  43: stop
  42: library
  41: load_metfamily_dependencies
   1: runApp
Error in library("xcms") : there is no package called ‘xcms’
```

Best
Niklas

**Comment by sneumann** [comment]
Thanks for reporting! 
So you refer to `docker pull sneumann/metfamily:latest` Hash `[04e38de9bb40](https://hub.docker.com/layers/sneumann/metfamily/latest/images/sha256-04e38de9bb40ea8773b9c332dc72a15fe5bca3e9ccd54e0598210a845c4aee10?context=explore)`
I can confirm xcms is not in there: `docker run --rm -it  sneumann/metfamily:latest R -e 'library(xcms)'` 
To avoid overly long container build times, we have a `metfamily-base` container with all the dependencies (supposedly) being installed in 
https://github.com/ipb-halle/MetFamily/blob/0c98d5db9fff8a006797d63a3452cd313696afd0/Dockerfile-base#L33
and then the `metfamily` image on top with only the MetFamily package and shiny app needing build and installation:
https://github.com/ipb-halle/MetFamily/blob/master/Dockerfile
Seems that `xcms` is not in https://github.com/ipb-halle/MetFamily/blob/master/DESCRIPTION and hence not installed.
Yet, it is loaded explicitly in https://github.com/ipb-halle/MetFamily/blob/0c98d5db9fff8a006797d63a3452cd313696afd0/R/R_packages.R#L18
and called during shiny startup in https://github.com/ipb-halle/MetFamily/blob/0c98d5db9fff8a006797d63a3452cd313696afd0/inst/MetFamily/server.R#L31
and at least one xcms function is called in 
https://github.com/ipb-halle/MetFamily/blob/0c98d5db9fff8a006797d63a3452cd313696afd0/R/FragmentMatrixFunctions.R#L1345
So it definitely needs to go back into the base image.
Yours,
Steffen

**Comment by nschan** [comment]
Thanks a lot for the quick fix, I will give it a try.
